-- MySQL Script generated by MySQL Workbench
-- Mon Nov  4 17:01:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema musicstream_pr2_g2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musicstream_pr2_g2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musicstream_pr2_g2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `musicstream_pr2_g2` ;

-- -----------------------------------------------------
-- Table `musicstream_pr2_g2`.`artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicstream_pr2_g2`.`artistas` (
  `artista_id` INT NOT NULL,
  `artista` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`artista_id`));

-- -----------------------------------------------------
-- Table `musicstream_pr2_g2`.`estadisticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicstream_pr2_g2`.`estadisticas` (
  `artista_id` INT NULL DEFAULT NULL,
  `listeners` INT NULL DEFAULT NULL,
  `playcount` INT NULL DEFAULT NULL,
  `artistas_similares` VARCHAR(100) NULL DEFAULT NULL,
  INDEX `artista_id_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `artista_id`
    FOREIGN KEY (`artista_id`)
    REFERENCES `musicstream_pr2_g2`.`artistas` (`artista_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `musicstream_pr2_g2`.`info_canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicstream_pr2_g2`.`info_canciones` (
  `artista_id` INT NULL DEFAULT NULL,
  `nombre_cancion_album` VARCHAR(255) NOT NULL,
  `tipo_album_cancion` VARCHAR(50) NULL DEFAULT NULL,
  `año_lanzamiento` YEAR NULL DEFAULT NULL,
  `género` VARCHAR(50) NULL DEFAULT NULL,
  INDEX `artista_id_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `artista_id`
    FOREIGN KEY (`artista_id`)
    REFERENCES `musicstream_pr2_g2`.`artistas` (`artista_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE); 

-- -----------------------------------------------------
-- Table `musicstream_pr2_g2`.`informacion_artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicstream_pr2_g2`.`informacion_artista` (
  `artista_id` INT NULL DEFAULT NULL,
  `biografia` TEXT NULL DEFAULT NULL,
  `pais_de_origen` VARCHAR(50) NULL DEFAULT NULL,
  `area_de_origen` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_nacimiento` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_inicio_actividad` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_fin_actividad` VARCHAR(50) NULL DEFAULT NULL,
  INDEX `artista_id_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `artista_id`
    FOREIGN KEY (`artista_id`)
    REFERENCES `musicstream_pr2_g2`.`artistas` (`artista_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE); 


-- -----------------------------------------------------
-- ESTA TABLA ES LA QUE TIENE LOS NULL (CREAR OPCIONAL) 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musicstream_pr2_g2`.`musicbrainz1` (
  `artista` TEXT NULL DEFAULT NULL,
  `pais_de_origen` TEXT NULL DEFAULT NULL,
  `area_de_origen` TEXT NULL DEFAULT NULL,
  `fecha_nacimiento` TEXT NULL DEFAULT NULL,
  `fecha_inicio_actividad` TEXT NULL DEFAULT NULL,
  `fecha_fin_actividad` TEXT NULL DEFAULT NULL,
  `artista_id` BIGINT NULL DEFAULT NULL,
  INDEX `artista_id` (`artista_id` ASC) VISIBLE); 


